# Generated by Django 5.2.4 on 2026-08-03 11:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('seller_name', models.CharField(default='KAVIN TEX', max_length=255)),
                ('seller_address', models.TextField(default='7-1/53, 22ND WARD, AMBETHKAR STREET, Tharamangalam')),
                ('seller_gstin', models.CharField(default='33BUUPR3263F2Z9', max_length=15)),
                ('seller_state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('seller_state_code', models.CharField(default='33', max_length=2)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField(blank=True, null=True)),
                ('buyer_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('place_of_supply', models.CharField(max_length=2)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('transport_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transport_address', models.TextField(blank=True, null=True)),
                ('transport_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('total_bundles', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_in_words', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
        ),
    ]
