# Generated by Django 5.2.4 on 2026-08-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='e_way_bill_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
