# Generated by Django 5.2.4 on 2025-08-01 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(help_text='Bill ID represents the invoice number', primary_key=True, serialize=False)),
                ('seller_name', models.TextField()),
                ('seller_address', models.TextField()),
                ('seller_gst_in', models.TextField()),
                ('seller_state_name_code', models.TextField()),
                ('buyer_name', models.TextField()),
                ('buyer_address', models.TextField()),
                ('buyer_gst_in', models.TextField()),
                ('buyer_state_name_code', models.TextField()),
                ('e_way_bill_no', models.TextField()),
                ('transport_mode', models.TextField()),
                ('transport_name', models.TextField()),
                ('transport_address', models.TextField()),
                ('transport_gst_in', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('mode_of_payment', models.TextField()),
                ('item_details', models.TextField()),
                ('total', models.CharField(blank=True, max_length=256, null=True)),
                ('cgst', models.CharField(blank=True, max_length=256, null=True)),
                ('sgst', models.CharField(blank=True, max_length=256, null=True)),
                ('igst', models.CharField(blank=True, max_length=256, null=True)),
                ('total_amount', models.TextField()),
                ('amount_in_words', models.TextField()),
                ('declaration', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
