# Generated by Django 5.2.4 on 2025-08-01 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('seller_name', models.CharField(default='KAVIN TEX', max_length=255)),
                ('seller_address', models.TextField(default='7-1/53, 22ND WARD, AMBETHKAR STREET, Tharamangalam')),
                ('seller_gstin', models.CharField(default='33BUUPR3263F2Z9', max_length=15)),
                ('seller_state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('seller_state_code', models.CharField(default='33', max_length=2)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField(blank=True, null=True)),
                ('buyer_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('place_of_supply', models.CharField(max_length=2)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_in_words', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('bundles', models.PositiveIntegerField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.invoice')),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
